const Drivetrains = {
  "4WD": { name: "4WD", displayOrder: 1 },
  "FWD": { name: "FWD", displayOrder: 2 },
  "RWD": { name: "RWD", displayOrder: 0 },
};

const Classes = {
  1: { name: "H1", drivetrainID: "FWD", displayOrder: 4 },
  2: { name: "H2", drivetrainID: "FWD", displayOrder: 3 },
  3: { name: "H2", drivetrainID: "RWD", displayOrder: 2 },
  4: { name: "H3", drivetrainID: "RWD", displayOrder: 1 },
  5: { name: "Group B", drivetrainID: "RWD", displayOrder: 0 },
  6: { name: "Group B", drivetrainID: "4WD", displayOrder: 11 },
  7: { name: "NR4", drivetrainID: "4WD", displayOrder: 8 },
  8: { name: "Rally4", drivetrainID: "FWD", displayOrder: 0 },
  9: { name: "S1600", drivetrainID: "FWD", displayOrder: 1 },
  10: { name: "S2000", drivetrainID: "4WD", displayOrder: 9 },
  11: { name: "F2 Kit", drivetrainID: "FWD", displayOrder: 2 },
  12: { name: "Group A", drivetrainID: "4WD", displayOrder: 10 },
  13: { name: "WRC 97-11", drivetrainID: "4WD", displayOrder: 5 },
  14: { name: "Rally2", drivetrainID: "4WD", displayOrder: 6 },
  17: { name: "WRC 17-21", drivetrainID: "4WD", displayOrder: 3 },
  19: { name: "WRC", drivetrainID: "4WD", displayOrder: 0 },
  20: { name: "JWRC", drivetrainID: "4WD", displayOrder: 2 },
  21: { name: "WRC2", drivetrainID: "4WD", displayOrder: 1 },
  22: { name: "Rally3", drivetrainID: "4WD", displayOrder: 7 },
  23: { name: "WRC 12-16", drivetrainID: "4WD", displayOrder: 4 },
};

const Surfaces = {
  "Asphalt": { name: "Asphalt", displayOrder: 1 },
  "Loose": { name: "Loose", displayOrder: 0 },
};

const Locations = {
  5: { name: "Mediterraneo", surfaceID: "Asphalt", displayOrder: 4 },
  6: { name: "Portugal", surfaceID: "Loose", displayOrder: 13 },
  7: { name: "Italia", surfaceID: "Loose", displayOrder: 7 },
  8: { name: "Estonia", surfaceID: "Loose", displayOrder: 6 },
  9: { name: "Scandia", surfaceID: "Loose", displayOrder: 8 },
  12: { name: "Mexico", surfaceID: "Loose", displayOrder: 4 },
  13: { name: "Chile", surfaceID: "Loose", displayOrder: 1 },
  14: { name: "Pacifico", surfaceID: "Loose", displayOrder: 0 },
  15: { name: "Finland", surfaceID: "Loose", displayOrder: 11 },
  16: { name: "Croatia", surfaceID: "Asphalt", displayOrder: 1 },
  17: { name: "Monte-Carlo", surfaceID: "Asphalt", displayOrder: 5 },
  18: { name: "Sweden", surfaceID: "Loose", displayOrder: 9 },
  24: { name: "Greece", surfaceID: "Loose", displayOrder: 2 },
  25: { name: "Japan", surfaceID: "Asphalt", displayOrder: 2 },
  26: { name: "Kenya", surfaceID: "Loose", displayOrder: 10 },
  27: { name: "Oceana", surfaceID: "Loose", displayOrder: 3 },
  28: { name: "Iberia", surfaceID: "Asphalt", displayOrder: 3 },
  29: { name: "Central Europe", surfaceID: "Asphalt", displayOrder: 0 },
  30: { name: "Latvia", surfaceID: "Loose", displayOrder: 12 },
  31: { name: "Poland", surfaceID: "Loose", displayOrder: 5 },
};

const Stages = {
  24: { name: "Asco", locationID: 5 },
  25: { name: "Ponte", locationID: 5 },
  26: { name: "Monte Cinto", locationID: 5 },
  28: { name: "Albarello", locationID: 5 },
  29: { name: "Capannace", locationID: 5 },
  30: { name: "Serra Di Cuzzioli", locationID: 5 },
  32: { name: "Maririe", locationID: 5 },
  33: { name: "Poggiola", locationID: 5 },
  34: { name: "Monte Alloradu", locationID: 5 },
  35: { name: "Ravin de Finelio", locationID: 5 },
  36: { name: "Cabanella", locationID: 5 },
  37: { name: "Moltifao", locationID: 5 },
  99: { name: "Baião", locationID: 6 },
  100: { name: "Caminha", locationID: 6 },
  101: { name: "Fridão", locationID: 6 },
  103: { name: "Marão", locationID: 6 },
  104: { name: "Ponte de Lima", locationID: 6 },
  105: { name: "Viana do Castelo", locationID: 6 },
  106: { name: "Ervideiro", locationID: 6 },
  108: { name: "Celeiro", locationID: 6 },
  109: { name: "Touca", locationID: 6 },
  110: { name: "Vila Boa", locationID: 6 },
  111: { name: "Carrazedo", locationID: 6 },
  112: { name: "Anjos", locationID: 6 },
  446: { name: "Fafe", locationID: 6 },
  447: { name: "Vila Pouca", locationID: 6 },
  448: { name: "Barbosa", locationID: 6 },
  449: { name: "Passos", locationID: 6 },
  450: { name: "Moreira do Rei", locationID: 6 },
  451: { name: "Ruivães", locationID: 6 },
  113: { name: "Rena Majore", locationID: 7 },
  114: { name: "Monte Olia", locationID: 7 },
  115: { name: "Littichedda", locationID: 7 },
  117: { name: "Alà del Sardi", locationID: 7 },
  118: { name: "Mamone", locationID: 7 },
  119: { name: "Li Pinnenti", locationID: 7 },
  120: { name: "Malti", locationID: 7 },
  122: { name: "Bassacutena", locationID: 7 },
  123: { name: "Bortigiadas", locationID: 7 },
  124: { name: "Sa Mela", locationID: 7 },
  125: { name: "Monte Muvri", locationID: 7 },
  126: { name: "Monte Acuto", locationID: 7 },
  320: { name: "Otepää", locationID: 8 },
  321: { name: "Rebaste", locationID: 8 },
  322: { name: "Nüpli", locationID: 8 },
  323: { name: "Truuta", locationID: 8 },
  324: { name: "Koigu", locationID: 8 },
  325: { name: "Kooraste", locationID: 8 },
  326: { name: "Elva", locationID: 8 },
  327: { name: "Metsalaane", locationID: 8 },
  328: { name: "Vahessaare", locationID: 8 },
  329: { name: "Külaaseme", locationID: 8 },
  330: { name: "Vissi", locationID: 8 },
  331: { name: "Vellavere", locationID: 8 },
  85: { name: "Holtjønn", locationID: 9 },
  86: { name: "Hengeltjønn", locationID: 9 },
  87: { name: "Fyresvatn", locationID: 9 },
  88: { name: "Russvatn", locationID: 9 },
  89: { name: "Tovsli", locationID: 9 },
  91: { name: "Kottjønn", locationID: 9 },
  93: { name: "Fordol", locationID: 9 },
  94: { name: "Fyresdal", locationID: 9 },
  95: { name: "Ljosdalstjønn", locationID: 9 },
  96: { name: "Dagtrolltjønn", locationID: 9 },
  97: { name: "Tovslioytjorn", locationID: 9 },
  98: { name: "Bergsøytjønn", locationID: 9 },
  127: { name: "El Chocolate", locationID: 12 },
  128: { name: "Otates", locationID: 12 },
  129: { name: "Ortega", locationID: 12 },
  130: { name: "Las Minas", locationID: 12 },
  131: { name: "Ibarrilla", locationID: 12 },
  133: { name: "Derramadero", locationID: 12 },
  134: { name: "El Brinco", locationID: 12 },
  136: { name: "Guanajuatito", locationID: 12 },
  137: { name: "Alfaro", locationID: 12 },
  138: { name: "Mesa Cuata", locationID: 12 },
  139: { name: "San Diego", locationID: 12 },
  140: { name: "El Mosquito", locationID: 12 },
  155: { name: "Bio Bío", locationID: 13 },
  156: { name: "Pulpería", locationID: 13 },
  157: { name: "Río Lía", locationID: 13 },
  159: { name: "María Las Cruces", locationID: 13 },
  160: { name: "Las Pataguas", locationID: 13 },
  161: { name: "Rere", locationID: 13 },
  162: { name: "El Poñen", locationID: 13 },
  163: { name: "Laja", locationID: 13 },
  164: { name: "Yumbel", locationID: 13 },
  165: { name: "Río Claro", locationID: 13 },
  166: { name: "Hualqui", locationID: 13 },
  167: { name: "Chivilingo", locationID: 13 },
  57: { name: "Talao", locationID: 14 },
  58: { name: "Talanghilirair", locationID: 14 },
  59: { name: "Sungai Kunit", locationID: 14 },
  60: { name: "Sangir Balai Janggo", locationID: 14 },
  61: { name: "South Solok", locationID: 14 },
  63: { name: "Kebun Raya Solok", locationID: 14 },
  64: { name: "Batukangkung", locationID: 14 },
  65: { name: "Abai", locationID: 14 },
  66: { name: "Moearaikoer", locationID: 14 },
  67: { name: "Bidaralam", locationID: 14 },
  68: { name: "Loeboekmalaka", locationID: 14 },
  69: { name: "Gunung Tujuh", locationID: 14 },
  204: { name: "Leustu", locationID: 15 },
  205: { name: "Lahdenkylä", locationID: 15 },
  206: { name: "Saakoski", locationID: 15 },
  207: { name: "Maahi", locationID: 15 },
  208: { name: "Painaa", locationID: 15 },
  209: { name: "Peltola", locationID: 15 },
  216: { name: "Päijälä", locationID: 15 },
  217: { name: "Ruokolahti", locationID: 15 },
  218: { name: "Honkanen", locationID: 15 },
  219: { name: "Venkajärvi", locationID: 15 },
  220: { name: "Vehmas", locationID: 15 },
  221: { name: "Hatanpää", locationID: 15 },
  344: { name: "Bliznec", locationID: 16 },
  345: { name: "Trakošćan", locationID: 16 },
  346: { name: "Vrbno", locationID: 16 },
  347: { name: "Zagorska Sela", locationID: 16 },
  348: { name: "Kumrovec", locationID: 16 },
  349: { name: "Grdanjci", locationID: 16 },
  350: { name: "Stojdraga", locationID: 16 },
  351: { name: "Mali Lipovec", locationID: 16 },
  352: { name: "Hartje", locationID: 16 },
  353: { name: "Kostanjevac", locationID: 16 },
  354: { name: "Krašić", locationID: 16 },
  355: { name: "Petruš Vrh", locationID: 16 },
  252: { name: "La Bollène-Vésubie - Peïra Cava", locationID: 17 },
  253: { name: "Peïra Cava - La Bollène-Vésubie", locationID: 17 },
  254: { name: "La Bollène-Vésubie - Col de Turini", locationID: 17 },
  255: { name: "Pra d'Alart", locationID: 17 },
  256: { name: "La Maïris", locationID: 17 },
  257: { name: "Baisse de Patronel", locationID: 17 },
  263: { name: "Saint-Léger-les-Mélèzes - La Bâtie-Neuve", locationID: 17 },
  264: { name: "La Bâtie-Neuve - Saint-Léger-les-Mélèzes", locationID: 17 },
  265: { name: "Moissière", locationID: 17 },
  266: { name: "Ancelle", locationID: 17 },
  267: { name: "Ravin de Coste Belle", locationID: 17 },
  268: { name: "Les Borels", locationID: 17 },
  440: { name: "Briançonnet - Entrevaux", locationID: 17 },
  441: { name: "Entrevaux - Briançonnet", locationID: 17 },
  442: { name: "Les Vénières", locationID: 17 },
  443: { name: "Parbiou", locationID: 17 },
  444: { name: "Le champ", locationID: 17 },
  445: { name: "Pertus", locationID: 17 },
  229: { name: "Hof-Finnskog", locationID: 18 },
  230: { name: "Åsnes", locationID: 18 },
  231: { name: "Spikbrenna", locationID: 18 },
  232: { name: "Lauksjøen", locationID: 18 },
  233: { name: "Åslia", locationID: 18 },
  234: { name: "Knapptjernet", locationID: 18 },
  241: { name: "Vargasen", locationID: 18 },
  242: { name: "Lövstaholm", locationID: 18 },
  243: { name: "Älgsjön", locationID: 18 },
  244: { name: "Ekshärad", locationID: 18 },
  245: { name: "Stora Jangen", locationID: 18 },
  246: { name: "Sunne", locationID: 18 },
  296: { name: "Gravia", locationID: 24 },
  297: { name: "Prosilio", locationID: 24 },
  298: { name: "Mariolata", locationID: 24 },
  299: { name: "Karoutes", locationID: 24 },
  300: { name: "Viniani", locationID: 24 },
  301: { name: "Delphi", locationID: 24 },
  302: { name: "Eptalofos", locationID: 24 },
  303: { name: "Lilea", locationID: 24 },
  304: { name: "Parnassós", locationID: 24 },
  305: { name: "Bauxites", locationID: 24 },
  306: { name: "Drosochori", locationID: 24 },
  307: { name: "Amfissa", locationID: 24 },
  308: { name: "Lake Mikawa", locationID: 25 },
  309: { name: "Kudarisawa", locationID: 25 },
  310: { name: "Oninotaira", locationID: 25 },
  311: { name: "Okuwacho", locationID: 25 },
  312: { name: "Habu Dam", locationID: 25 },
  313: { name: "Habucho", locationID: 25 },
  314: { name: "Nenoue Plateau", locationID: 25 },
  315: { name: "Tegano", locationID: 25 },
  316: { name: "Higashino", locationID: 25 },
  317: { name: "Hokono Lake", locationID: 25 },
  318: { name: "Nenoue Highlands", locationID: 25 },
  319: { name: "Nakatsugawa", locationID: 25 },
  332: { name: "Malewa", locationID: 26 },
  333: { name: "Tarambete", locationID: 26 },
  334: { name: "Moi North", locationID: 26 },
  335: { name: "Marula", locationID: 26 },
  336: { name: "Wileli", locationID: 26 },
  337: { name: "Kingono", locationID: 26 },
  338: { name: "Soysambu", locationID: 26 },
  339: { name: "Mbaruk", locationID: 26 },
  340: { name: "Sugunoi", locationID: 26 },
  341: { name: "Nakuru", locationID: 26 },
  342: { name: "Kanyawa", locationID: 26 },
  343: { name: "Kanyawa - Nakura", locationID: 26 },
  356: { name: "Oakleigh", locationID: 27 },
  357: { name: "Doctors Hill", locationID: 27 },
  358: { name: "Mangapai", locationID: 27 },
  359: { name: "Brynderwyn", locationID: 27 },
  360: { name: "Taipuha", locationID: 27 },
  361: { name: "Mareretu", locationID: 27 },
  362: { name: "Waiwera", locationID: 27 },
  363: { name: "Tahekeroa", locationID: 27 },
  364: { name: "Noakes Hill", locationID: 27 },
  365: { name: "Orewa", locationID: 27 },
  366: { name: "Tahekeroa - Orewa", locationID: 27 },
  367: { name: "Makarau", locationID: 27 },
  274: { name: "Santes Creus", locationID: 28 },
  275: { name: "Valldossera", locationID: 28 },
  276: { name: "Campdasens", locationID: 28 },
  277: { name: "Pontils", locationID: 28 },
  278: { name: "Montagut", locationID: 28 },
  279: { name: "Aiguamúrcia", locationID: 28 },
  285: { name: "Alforja", locationID: 28 },
  286: { name: "Les Irles", locationID: 28 },
  287: { name: "L'Argentera", locationID: 28 },
  288: { name: "Les Voltes", locationID: 28 },
  289: { name: "Montclar", locationID: 28 },
  290: { name: "Botareli", locationID: 28 },
  368: { name: "Rouské", locationID: 29 },
  369: { name: "Lukoveček", locationID: 29 },
  370: { name: "Raztoka", locationID: 29 },
  371: { name: "Žabárna", locationID: 29 },
  372: { name: "Provodovice", locationID: 29 },
  373: { name: "Chvalčov", locationID: 29 },
  374: { name: "Vítová", locationID: 29 },
  375: { name: "Brusné", locationID: 29 },
  376: { name: "Libosváry", locationID: 29 },
  377: { name: "Rusava", locationID: 29 },
  378: { name: "Osíčko", locationID: 29 },
  379: { name: "Příkazy", locationID: 29 },
  380: { name: "Vecpils", locationID: 30 },
  381: { name: "Kaģene", locationID: 30 },
  382: { name: "Mazilmāja", locationID: 30 },
  383: { name: "Ķirsīts", locationID: 30 },
  384: { name: "Baznīca", locationID: 30 },
  385: { name: "Stroķacs", locationID: 30 },
  386: { name: "Podnieki", locationID: 30 },
  387: { name: "Dinsdurbe", locationID: 30 },
  388: { name: "Kalvene", locationID: 30 },
  389: { name: "Cērpi", locationID: 30 },
  390: { name: "Krote", locationID: 30 },
  391: { name: "Kalēti", locationID: 30 },
  392: { name: "Swietajno", locationID: 31 },
  393: { name: "Jelonek", locationID: 31 },
  394: { name: "Gajrowskie", locationID: 31 },
  395: { name: "Pietrasze", locationID: 31 },
  396: { name: "Dybowo", locationID: 31 },
  397: { name: "Chełchy", locationID: 31 },
  398: { name: "Mikolajki", locationID: 31 },
  399: { name: "Zawada", locationID: 31 },
  400: { name: "Gmina Mragowo", locationID: 31 },
  401: { name: "Czerwonki", locationID: 31 },
  402: { name: "Kosewo", locationID: 31 },
  403: { name: "Probark", locationID: 31 },
};

export const getDrivetrainIds = () =>
  Object.keys(Drivetrains).sort((a, b) => Drivetrains[a].displayOrder - Drivetrains[b].displayOrder);

export const getClassIds = (drivetrainID) =>
  Object.keys(Classes)
    .filter(id => !drivetrainID || Classes[id].drivetrainID === drivetrainID)
    .sort((a, b) => Classes[a].displayOrder - Classes[b].displayOrder)
    .map(Number);

export const getClassName = (classId) => Classes[classId]?.name;

export const getSurfaceIds = () =>
  Object.keys(Surfaces).sort((a, b) => Surfaces[a].displayOrder - Surfaces[b].displayOrder);

export const getLocationIds = (surfaceID) =>
  Object.keys(Locations)
    .filter(id => !surfaceID || Locations[id].surfaceID === surfaceID)
    .sort((a, b) => Locations[a].displayOrder - Locations[b].displayOrder)
    .map(Number);

export const getLocationName = (locationId) => Locations[locationId]?.name;

export const getStageIds = (locationId) =>
  Object.keys(Stages)
    .filter(id => !locationId || Stages[id].locationID === locationId)
    .map(Number);

export const getStageName = (stageId) => Stages[stageId]?.name;
